import bcrypt from 'bcryptjs';

const data = {
  mainCourse: [
    {
      name: 'Beef Burger',
      slug: 'beef-burger',
      category: 'mainCourse',
      price: 8.5,
      image: '/images/main-course/beef-burger.png',
      introduction:
        'Flame-grilled angus beef burger with classic Texas smoky BBQ sauce. The burger is filled with crisp fresh lettue, sour cucumber and gourmet tomatoes. There is tasty mayo in it, wrapping with toasted sesame seed bread.',
      weight: 'Weight: 296 grams',
      protein: 'Protein: 34 grams',
      fat: 'Fat: 24 grams',
      carbohydrate: 'Carbohydrate: 49.3 grams',
      Na: 'Na: 1057mg',
    },
    {
      name: 'Chicken Burger',
      slug: 'chicken-burger',
      category: 'mainCourse',
      price: 7,
      image: '/images/main-course/chicken-burger.png',
      introduction:
        'Grilled chicken breast burger, the chicken is super tender and juicy. There is melted cheese, onion rings and premium smoke flavored bacon in it. Fresh lettue and tomato, together with BBQ sauce and mayo in the burger. The sesame seed bun is toasted.',
      weight: 'Weight: 278 grams',
      protein: 'Protein: 27 grams',
      fat: 'Fat: 21 grams',
      carbohydrate: 'Carbohydrate: 51.5 grams',
      Na: 'Na: 1013mg',
    },
    {
      name: 'Double Chicken Burger',
      slug: 'double-chicken-burger',
      category: 'mainCourse',
      price: 9,
      image: '/images/main-course/double-chicken-burger.png',
      introduction:
        'Double crunchy and juicy fried chicken breast fillet burger. The delicious burger is filled with fresh lettue, tomatoes, classic sweet chilli sauce and mayo. The burger is wrapped with toasted sesame bread.',
      weight: 'Weight: 304 grams',
      protein: 'Protein: 36 grams',
      fat: 'Fat: 25 grams',
      carbohydrate: 'Carbohydrate: 54.7 grams',
      Na: 'Na: 1148mg',
    },
    {
      name: 'Fish Burger',
      slug: 'fish-burger',
      category: 'mainCourse',
      price: 7.5,
      image: '/images/main-course/fish-burger.png',
      introduction:
        'We use high quality hoki from New Zealand to make this burger. The fried hoki fillet is crispy and tender. Mustard and mayonnaise on the toasted soft bread, with fresh veggies in it.',
      weight: 'Weight: 282 grams',
      protein: 'Protein: 29 grams',
      fat: 'Fat: 17 grams',
      carbohydrate: 'Carbohydrate: 49.4 grams',
      Na: 'Na: 985mg',
    },
    {
      name: 'Prawn Burger',
      slug: 'prawn-burger',
      category: 'mainCourse',
      price: 9.5,
      image: '/images/main-course/prawn-burger.png',
      introduction:
        'Crispy fried prawns in the burger. Fresh lettuce, sour cucumbers and onion rings are in the burger. The melted cheese and mayonnaise make it taste even better.',
      weight: 'Weight: 275 grams',
      protein: 'Protein: 32 grams',
      fat: 'Fat: 20 grams',
      carbohydrate: 'Carbohydrate: 52.6 grams',
      Na: 'Na: 971mg',
    },
    {
      name: 'Spicy Chicken Burger',
      slug: 'spicy-chicken-burger',
      category: 'mainCourse',
      price: 7.5,
      image: '/images/main-course/spicy-chicken-burger.png',
      introduction:
        'Thick and crunchy fried chicken breast fillet. Mayonnaise, lettuce, tomatoes and our secret spicy sauce on a toasted sesame seed bun.',
      weight: 'Weight: 284 grams',
      protein: 'Protein: 25 grams',
      fat: 'Fat: 19 grams',
      carbohydrate: 'Carbohydrate: 47.9 grams',
      Na: 'Na: 993mg',
    },
    {
      name: 'Whole Roast Chicken',
      slug: 'whole-roast-chicken',
      category: 'mainCourse',
      price: 14.5,
      image: '/images/main-course/whole-roast-chicken.png',
      introduction:
        'Our popular whole roast chicken with spices and herbs, we also provide several sauces for you to choose. We offer sweet chilli sauce, smoky BBQ sauce and tomato sauce, etc. This roast chicken is perfect for family and friends to enjoy.',
      weight: 'Weight: 875 grams',
      protein: 'Protein: 56 grams',
      fat: 'Fat: 29 grams',
      carbohydrate: 'Carbohydrate: 72.6 grams',
      Na: 'Na: 1247mg',
    },
    {
      name: 'Chicken Wrap',
      slug: 'chicken-wrap',
      category: 'mainCourse',
      price: 6,
      image: '/images/main-course/chicken-wrap.png',
      introduction:
        'The Mexican flavor fried chicken fillet wrap. There are fresh cucumbers and lettuce in the chicken wrap. Mayonnaise and hot sauce create an amazing flavor.',
      weight: 'Weight: 246 grams',
      protein: 'Protein: 18 grams',
      fat: 'Fat: 15 grams',
      carbohydrate: 'Carbohydrate: 37.8 grams',
      Na: 'Na: 931mg',
    },
  ],
  sideDishes: [
    {
      name: 'Crispy Chicken Drumsticks',
      slug: 'crispy-chicken-drumsticks',
      category: 'sideDishes',
      price: 3,
      image: '/images/side-dishes/crispy-chicken-drumsticks.png',
      introduction:
        'Spicy and crispy chicken drumsticks. Good for snacks and entertainment time. We offer BBQ sauce and tomato sauce.',
      weight: 'Weight: 124 grams',
      protein: 'Protein: 12 grams',
      fat: 'Fat: 10 grams',
      carbohydrate: 'Carbohydrate: 23.6 grams',
      Na: 'Na: 748mg',
    },
    {
      name: 'Crispy Chicken Wings',
      slug: 'crispy-chicken-wings',
      category: 'sideDishes',
      price: 5.5,
      image: '/images/side-dishes/crispy-chicken-wings.png',
      introduction:
        'Fried chicken wings with spicy flavor. You can choose from several sauces. The chicken wings are crispy and juicy.',
      weight: 'Weight: 191 grams',
      protein: 'Protein: 15 grams',
      fat: 'Fat: 11 grams',
      carbohydrate: 'Carbohydrate: 26.8 grams',
      Na: 'Na: 814mg',
    },
    {
      name: 'Peppered Chicken Nuggets',
      slug: 'peppered-chicken-nuggets',
      category: 'sideDishes',
      price: 4.5,
      image: '/images/side-dishes/peppered-chicken-nuggets.png',
      introduction:
        'Delicious chicken nuggets with black pepper flavor. The sweet chilli sauce make the nuggets taste even better.',
      weight: 'Weight: 237 grams',
      protein: 'Protein: 17 grams',
      fat: 'Fat: 13 grams',
      carbohydrate: 'Carbohydrate: 42.5 grams',
      Na: 'Na: 876mg',
    },
    {
      name: 'Spicy Chicken Popcorn',
      slug: 'spicy-chicken-popcorn',
      category: 'sideDishes',
      price: 5,
      image: '/images/side-dishes/spicy-chicken-popcorn.png',
      introduction:
        'Hot and spicy chicken popcorn. Perfect for parties, you can enjoy this chicken popcorn with your friends and family.',
      weight: 'Weight: 182 grams',
      protein: 'Protein: 10 grams',
      fat: 'Fat: 9 grams',
      carbohydrate: 'Carbohydrate: 19.7 grams',
      Na: 'Na: 692mg',
    },
    {
      name: 'Crispy Chicken Fillet',
      slug: 'crispy-chicken-fillet',
      category: 'sideDishes',
      price: 7.5,
      image: '/images/side-dishes/crispy-chicken-fillet.png',
      introduction:
        ' Big, juicy and crunchy fried chicken fillet. We offer sweet chilli sauce and smoky BBQ sauce.',
      weight: 'Weight: 318 grams',
      protein: 'Protein: 27 grams',
      fat: 'Fat: 23 grams',
      carbohydrate: 'Carbohydrate: 52.6 grams',
      Na: 'Na: 1204mg',
    },
    {
      name: 'Roast Chicken Wings',
      slug: 'roast-chicken-wings',
      category: 'sideDishes',
      price: 6,
      image: '/images/side-dishes/roast-chicken-wings.png',
      introduction:
        'Classic roast chicken wings with excellent flavor. You can add any sauce you want. Good for snacks.',
      weight: 'Weight: 197 grams',
      protein: 'Protein: 13 grams',
      fat: 'Fat: 10 grams',
      carbohydrate: 'Carbohydrate: 28.3 grams',
      Na: 'Na: 835mg',
    },
  ],
  drinks: [
    {
      name: 'Coffee',
      slug: 'coffee',
      category: 'drinks',
      price: 3.5,
      image: '/images/drinks/coffee.png',
      introduction:
        'We have many categories of coffee, Latte, Cappuccino, Espresso, Black, Americano and so on.',
      calories: 'Calories: 87Cal',
    },
    {
      name: 'Milk',
      slug: 'milk',
      category: 'drinks',
      price: 3,
      image: '/images/drinks/milk.png',
      introduction:
        'A glass of hot milk is a good start of the day. Our milk is very fresh.',
      calories: 'Calories: 132 Cal',
    },
    {
      name: 'Orange Juice',
      slug: 'orange-juice',
      category: 'drinks',
      price: 2.5,
      image: '/images/drinks/orange-juice.png',
      introduction:
        'We offer fresh orange juice. We only use the best oranges to make the orange juice.',
      calories: 'Calories: 121 Cal',
    },
    {
      name: 'Milk Tea',
      slug: 'milk-tea',
      category: 'drinks',
      price: 5,
      image: '/images/drinks/milk-tea.png',
      introduction:
        'We use fresh milk and high quality tea to create the best flavor milk tea.',
      calories: 'Calories: 142 Cal',
    },
    {
      name: 'Pepsi',
      slug: 'pepsi',
      category: 'drinks',
      price: 2,
      image: '/images/drinks/pepsi.png',
      introduction: 'We offer classic Pepsi and no sugar version Pepsi.',
      calories: 'Calories: 186 Cal',
    },
    {
      name: 'Fanta',
      slug: 'fanta',
      category: 'drinks',
      price: 2,
      image: '/images/drinks/fanta.png',
      introduction:
        'Fanta is a very popular brand with the classic orange flavor.',
      calories: 'Calories: 179 Cal',
    },
    {
      name: 'Sprite',
      slug: 'sprite',
      category: 'drinks',
      price: 2,
      image: '/images/drinks/sprite.png',
      introduction:
        'Sprite is a good choice with the burgers and fried chicken wings.',
      calories: 'Calories: 173 Cal',
    },
  ],
  users: [
    {
      name: 'Amy',
      email: 'amy987@google.com',
      username: 'amy987',
      password: bcrypt.hashSync('987654'),
    },
    {
      name: 'Mike',
      email: 'mike456@google.com',
      username: 'mike456',
      password: bcrypt.hashSync('234567'),
    },
    {
      name: 'Tom',
      email: 'tom321@google.com',
      username: 'tom321',
      password: bcrypt.hashSync('123456'),
    },
  ],
  restaurants: [
    {
      name: 'Wonderful Meal Sydney',
      slug: 'Wonderful-Meal-Sydney',
      orderType: 'Pick Up(In Store) & Delivery',
      address: '12 Liverpool St, Surry Hills, NSW, 2010, Australia',
      hours: 'Mon-Wed: 10am-2am, Thu-Fri: 10am-11pm, Sat-Sun: Open 24 hours',
    },
    {
      name: 'Wonderful Meal Melbourne',
      slug: 'Wonderful-Meal-Melbourne',
      orderType: 'Pick Up(In Store) & Delivery',
      address: '26 Collins St, Docklands, VIC, 3008, Australia',
      hours: 'Sun-Thu: 10am-10pm, Fri-Sat: 10am-4am',
    },
    {
      name: 'Wonderful Meal Brisbane',
      slug: 'Wonderful-Meal-Brisbane',
      orderType: 'Pick Up(In Store) & Delivery',
      address: '57 George St, South Brisbane, QLD, 4101, Australia',
      hours: 'Mon-Thu: 9am-10pm, Fri-Sat: 9am-12am',
    },
    {
      name: 'Wonderful Meal Perth',
      slug: 'Wonderful-Meal-Perth',
      orderType: 'Pick Up(In Store) & Delivery',
      address: '72 James St, Subiaco, WA, 6008, Australia',
      hours: 'Sun-Thu: 10am-9:30pm, Fri-Sat: 10am-10pm',
    },
    {
      name: 'Wonderful Meal Adelaide',
      slug: 'Wonderful-Meal-Adelaide',
      orderType: 'Pick Up(In Store)',
      address: '41 Wright St, Norwood, SA, 5067, Australia',
      hours: 'Mon-Fri: 9am-6:30pm, Sat-Sun: 10am-5pm',
    },
  ],
};
export default data;
