const data = {
  mainCourse: [
    {
      name: 'Beef Burger',
      slug: 'beef-burger',
      category: 'main course',
      price: 8.5,
      image: '/images/main-course/beef-burger.png',
      introduction:
        'Flame-grilled angus beef burger with fresh lettue, tasty mayo and smoky BBQ sauce',
    },
    {
      name: 'Chicken Burger',
      slug: 'chicken-burger',
      category: 'main course',
      price: 7,
      image: '/images/main-course/chicken-burger.png',
      introduction:
        'Grilled chicken breast burger with fresh lettue and delicious mayo',
    },
    {
      name: 'Double Chicken Burger',
      slug: 'double-chicken-burger',
      category: 'main course',
      price: 9,
      image: '/images/main-course/double-chicken-burger.png',
      introduction:
        'Double crispy chicken breast burger with fresh lettue and delicious mayo',
    },
    {
      name: 'Fish Burger',
      slug: 'fish-burger',
      category: 'main course',
      price: 7.5,
      image: '/images/main-course/fish-burger.png',
      introduction:
        ' Crispy fried fish fillet burger with fresh lettue and delicious mayo',
    },
    {
      name: 'Shrimp Burger',
      slug: 'shrimp-burger',
      category: 'main course',
      price: 9.5,
      image: '/images/main-course/shrimp-burger.png',
      introduction: ' Juicy and delicious shrimp burger, mixed vegetables',
    },
    {
      name: 'Spicy Chicken Burger',
      slug: 'spicy-chicken-burger',
      category: 'main course',
      price: 7.5,
      image: '/images/main-course/spicy-chicken-burger.png',
      introduction: ' Hot and spicy chicken burger, mixed vegetables and mayo',
    },
    {
      name: 'Whole Roast Chicken',
      slug: 'whole-roast-chicken',
      category: 'main course',
      price: 14.5,
      image: '/images/main-course/whole-roast-chicken.png',
      introduction:
        ' Whole roast chicken with spices and herbs, perfect for family and friends to enjoy',
    },
    {
      name: 'Chicken Wrap',
      slug: 'chicken-wrap',
      category: 'main course',
      price: 6,
      image: '/images/main-course/chicken-wrap.png',
      introduction: ' Mexican flavor chicken wrap with fresh veggies',
    },
  ],
  sideDishes: [
    {
      name: 'Crispy Chicken Drumsticks',
      slug: 'crispy-chicken-drumsticks',
      category: 'side dishes',
      price: 3,
      image: '/images/side-dishes/crispy-chicken-drumsticks.png',
      introduction: ' Spicy and crispy chicken drumsticks  ',
    },
    {
      name: 'Crispy Chicken Wings',
      slug: 'crispy-chicken-wings',
      category: 'side dishes',
      price: 5.5,
      image: '/images/side-dishes/crispy-chicken-wings.png',
      introduction: ' Spicy and crispy chicken wings  ',
    },
    {
      name: 'Peppered Chicken Nuggets',
      slug: 'peppered-chicken-nuggets',
      category: 'side dishes',
      price: 4.5,
      image: '/images/side-dishes/peppered-chicken-nuggets.png',
      introduction: ' Peppered chicken nuggets with sweet chilli sauce  ',
    },
    {
      name: 'Spicy Chicken Popcorn',
      slug: 'spicy-chicken-popcorn',
      category: 'side dishes',
      price: 5,
      image: '/images/side-dishes/spicy-chicken-popcorn.png',
      introduction: ' Hot and spicy chicken popcorn  ',
    },
    {
      name: 'Crispy Chicken Fillet',
      slug: 'crispy-chicken-fillet',
      category: 'side dishes',
      price: 7.5,
      image: '/images/side-dishes/crispy-chicken-fillet.png',
      introduction: ' Big chunks of crispy chicken fillet  ',
    },
    {
      name: 'Roast Chicken Wings',
      slug: 'roast-chicken-wings',
      category: 'side dishes',
      price: 6,
      image: '/images/side-dishes/roast-chicken-wings.png',
      introduction: ' Roast chicken wings with excellent flavor  ',
    },
  ],
  drinks: [
    {
      name: 'Coffee',
      slug: 'coffee',
      category: 'drinks',
      price: 3.5,
      image: '/images/drinks/coffee.png',
      introduction: ' Coffee  ',
    },
    {
      name: 'Milk',
      slug: 'milk',
      category: 'drinks',
      price: 3,
      image: '/images/drinks/milk.png',
      introduction: ' Milk  ',
    },
    {
      name: 'Orange Juice',
      slug: 'orange-juice',
      category: 'drinks',
      price: 2.5,
      image: '/images/drinks/orange-juice.png',
      introduction: ' Orange Juice  ',
    },
    {
      name: 'Milk Tea',
      slug: 'milk-tea',
      category: 'drinks',
      price: 5,
      image: '/images/drinks/milk-tea.png',
      introduction: ' Milk Tea  ',
    },
    {
      name: 'Pepsi',
      slug: 'pepsi',
      category: 'drinks',
      price: 2,
      image: '/images/drinks/pepsi.png',
      introduction: ' Pepsi  ',
    },
    {
      name: 'Fanta',
      slug: 'fanta',
      category: 'drinks',
      price: 2,
      image: '/images/drinks/fanta.png',
      introduction: ' Fanta  ',
    },
    {
      name: 'Sprite',
      slug: 'sprite',
      category: 'drinks',
      price: 2,
      image: '/images/drinks/sprite.png',
      introduction: ' Sprite  ',
    },
  ],
};
export default data;
